[project]
name = "clash"
version = "0.1.0"
description = "Clash Compiler"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "automata-lib>=9.1.2",
    "llvmlite>=0.45.1",
    "nuitka>=2.8.6",
    "pyfiglet>=1.0.4",
    "pyinstaller>=6.16.0",
    "pytest>=8.4.2",
]
